### ISSUE TITLE
Genesis block error

### ISSUE THREAD

**Issue by Maikkeyy** [ESD6-blockr/blockr-dev-stack#6]
When starting the blockr-dev-stack project with docker-compose up --build, an invalid message error is triggered. 

![image](https://user-images.githubusercontent.com/19424609/55788035-e2143180-5ab7-11e9-8c7b-88493f6f5308.png)

**Comment by arnoudbevers** [comment]
Deze error ook gehad op de SecLab (inloggegevens PTS-S67-A)
De .gitmodules aanpassen zodat de validator naar de develop branch wijst heeft niet gewerkt
Later volgt er een error 'Cannot read property "blockHeader" of undefined' als gevolg van de eerste error

**Comment by saltz** [comment]
The issue is fixed in #7. Refer to the updated readme on how to prevent this error.
